# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    build:
      html:
        # HTML output
        - python -m sphinx -T -b html docs/source $READTHEDOCS_OUTPUT/html -D language=en

      pdf:
        # 1) Build LaTeX into a TEMP directory (not the RTD pdf dir)
        - mkdir -p _build/latex
        - python -m sphinx -T -b latex docs/source _build/latex -D language=en

        # 2) Run latexmk in that temp directory
        #    (latexmkrc is assumed to live in the repo root; adjust ../latexmkrc if needed)
        - cd _build/latex && latexmk -r ../latexmkrc -pdf -f -dvi- -ps- -jobname=nhs-postprocessing -interaction=nonstopmode

        # 3) Copy ONLY the final PDF into the RTD pdf output dir
        - mkdir -p $READTHEDOCS_OUTPUT/pdf
        - cp _build/latex/nhs-postprocessing.pdf $READTHEDOCS_OUTPUT/pdf/nhs-postprocessing.pdf

      epub:
        # ePub output
        - python -m sphinx -T -b epub docs/source $READTHEDOCS_OUTPUT/epub -D language=en

# Use Sphinx config under docs/source
sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - setup.py
    - requirements: docs/requirements.txt

# # Required 
# version: 2

# # Build PDF & ePub
# formats:
#   - epub
#   - pdf

# build:
#   os: "ubuntu-22.04"
#   tools:
#     python: "3.11"

# # Build documentation in the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/source/conf.py

# python:
#   install:
#   - method: pip
#     path : .
#     extra_requirements: 
#       - setup.py
#   - requirements: docs/requirements.txt
