version: 2

# No PDF/EPUB builds on RTD for now
#formats: []   # or just omit the whole `formats:` block
formats:
  - epub
  #- pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - setup.py
    - requirements: docs/requirements.txt



# # Required 
# version: 2

# # Build PDF & ePub
# formats:
#   - epub
#   - pdf

# build:
#   os: "ubuntu-22.04"
#   tools:
#     python: "3.11"

# # Build documentation in the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/source/conf.py

# python:
#   install:
#   - method: pip
#     path : .
#     extra_requirements: 
#       - setup.py
#   - requirements: docs/requirements.txt
